### ISSUE TITLE
Adding a Redis database

### ISSUE THREAD

**Issue by bkoz** [dudash/openshift-workshops#18]
Not sure if you guys are interested in adding a redis DB to the guestbook. I did not want to hack up the workshop source and create a PR if you feel it's overkill. 

$ oc new-app docker.io/kubeguide/redis-master

Wait for the redis pod to become ready then redeploy the guestbook.

$ oc deploy guestbook --latest

**Comment by brandoncox** [comment]
I don't think it's overkill. That lab is brief IMO, so I think it would be a good addition to add more substance. I guess it would only work for the online version of the labs.
