### ISSUE TITLE
Updating BEER_ME doesn't seem to change the layout

### ISSUE THREAD

**Issue by brandoncox** [dudash/openshift-workshops#5]
Reported by J.Osborne and I've seen the same behavior. When you update the variable redeploy to OCP, the code changes but the UI never updates. Creating a bug here so I do not forget to investigate and apply a fix.

**Comment by dudash** [comment]
This will work in the master branch and in TAG v1.1.1.  Make sure you aren't trying to do it in a older release tag.

Relevant source code is here:
https://github.com/dudash/openshift-workshops/blob/master/dc-metro-map/routes/index.js

**Comment by brandoncox** [comment]
I verified that this works as expected. Closing.
